version: "3"
services: 
    node-app:
        image: yolix/node-app:test
        networks: 
            - app-network
    nginx:
        image: nginx
        ports: 
            - 80:80
        networks: 
            - app-network
        volumes: 
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on: 
            - node-app
networks: 
    app-network:
        driver: bridge